jobs:
  include:
    - stage: danger
      language: ruby
      rvm: 2.5.1
      install: bundle install
      script: bundle exec danger --fail-on-errors=true
      if: type = pull_request
    - stage: test
      language: rust
      rust: stable
      cache: cargo
    - language: rust
      rust: beta
      cache: cargo
      if: type = pull_request AND branch = master
    - language: rust
      rust: nightly
      cache: cargo
      if: type = pull_request AND branch = master
    - stage: docs
      language: rust
      rust: stable
      cache: cargo
      before_script:
        - |
            pip install 'travis-cargo<0.2' --user &&
            export PATH=$HOME/.local/bin:$PATH
      script:
        - |
            travis-cargo build &&
            travis-cargo doc
      after_success:
        - travis-cargo doc-upload
      if: type = push AND branch IN (master, develop)
  allow_failures:
    - rust: nightly
  fast_finish: true

stages:
  - danger
  - test
  - docs

notifications:
  email: false
