jobs:
  include:
    - stage: danger
      language: ruby
      rvm: 2.5.1
      install: bundle install
      script: bundle exec danger
    - language: rust
      rust: stable
      cache: cargo
    - language: rust
      rust: beta
      cache: cargo
    - language: rust
      rust: nightly
      cache: cargo
  allow_failures:
    - rust: nightly
  fast_finish: true

stages:
  - danger
  - test

# rust:
#   - stable
#   - beta
#   - nightly
# cache: cargo
# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true
# jobs:
#   include:
#     - stage: danger
#       rvm: 2.5.1
#       rust:
#       cache:
#       install: bundle install
#       script: bundle exec danger
# stages:
#   - danger
#   - test

notifications:
  email: false
