language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
install: bundle install
before_script: bundle exec danger
notifications:
  email: false
