language: rust

rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
jobs:
  include:
    - stage: danger
      before_install: skip
      install: bundle install
      script: bundle exec danger
stages:
  - danger
  - test

notifications:
  email: false
