[package]
name = "ghtool-util"
version = "0.1.0"
authors = ["Søren Mortensen <soren@sorenmortensen.com>"]
license = "Apache-2.0"
description = "Utilities for ghtool"
publish = false

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
